name: Codybryant
favicon: null
layout_spectrum: 0.5547798
typography_spectrum: 0.7008593
title: Photography by Cody Bryant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B59887'
    - '#CFCFD8'
    - '#4B88AB'
    - '#036E91'
    - '#033954'
  brandStrength: 0.5837809
  lightness: 0.6911923
  saturation: 0.2024704
  rhythmicContrast: 0.6417831
purpose: []
