layout_spectrum: 0.5547798
typography_spectrum: 0.7008593
color:
  saturation: 0.2024704
  lightness: 0.6911923
  brandStrength: 0.5837809
  brandColors:
    - '#B59887'
    - '#CFCFD8'
    - '#4B88AB'
    - '#036E91'
    - '#033954'
  rhythmicContrast: 0.6417831
name: Codybryant
